#
#  Copyright (C) 2016-2026 Roman Pauer
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to deal in
#  the Software without restriction, including without limitation the rights to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#  of the Software, and to permit persons to whom the Software is furnished to do
#  so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#

import os
import sys
import subprocess
import shutil
import json

# set help text
vars = Variables('custom.py')
vars.Add(EnumVariable('debug', 'Debug level (0 = release version)', '0',
                                 allowed_values=('0', '1', '2'),
                                 ignorecase=2))
vars.Add(BoolVariable('mingw', 'Use MinGW instead of default compiler', False))
vars.Add(EnumVariable('device', 'Set target device', '',
                                 allowed_values=('', 'pc-windows', 'pc-linux', 'arm-linux', 'pyra', 'pc64-linux', 'arm64-linux', 'riscv64-linux', 'pc64-windows', 'pc64-darwin', 'arm64-darwin', 'web'),
                                 ignorecase=2))
vars.Add(BoolVariable('llasm', 'Compile llasm version instead of native version (when both are possible)', False))
vars.Add(BoolVariable('ptrofs', 'Compile llasm version with offset pointers instead of llasm version with direct pointers (when both are possible)', False))
vars.Add(EnumVariable('speexdsp', 'Use SpeexDSP library for higher quality resampling', '0',
                                 allowed_values=('0', '1'),
                                 ignorecase=2))
env = Environment(variables = vars)

debug = int(env['debug'])
mingw = env['mingw']
device = env['device']
prefer_llasm = env['llasm']
prefer_ptrofs64 = env['ptrofs']
speexdsp = int(env['speexdsp'])
clean = env.GetOption('clean')
program_name = 'SR-Main'


if device == '':
    device = 'pc-linux'
    if env['PLATFORM'] == 'win32':
        device = 'pc-windows'
    elif env['PLATFORM'] == 'darwin':
        device = 'arm64-darwin'
        machine = os.uname()[4]
        if machine == 'x86_64':
            device = 'pc64-darwin'
    elif env['PLATFORM'] == 'posix':
        machine = os.uname()[4]
        if machine.startswith('arm'):
            device = 'arm-linux'
        elif machine == 'aarch64':
            device = 'arm64-linux'
        elif machine == 'riscv64':
            device = 'riscv64-linux'
        elif machine == 'x86_64' or machine == 'amd64':
            device = 'pc64-linux'
    env['device'] = device
    print("\nYou didn't set any target device (parameter 'device').")
    print("'" + device + "' will be used for compiling.\n")

Help(vars.GenerateHelpText(env))

Help("""
Environment variables:
  - PATH_INC: paths to find include files
  - PATH_LIB: paths to find library files
""")

llasm_version = False

if mingw:
    env = Environment(tools = ['mingw'])
elif env['CC'] == 'cl' and device == 'pc-windows':
    env = Environment(TARGET_ARCH = 'x86')

use_pic = False

# default settings
if env['CC'] == 'cl':
    env.Append(CCFLAGS   = '/O2 /W3 /D_CRT_SECURE_NO_WARNINGS',
               LINKFLAGS = '/INCREMENTAL:NO'
              )

    if debug <= 0:
        env.Append(LINKFLAGS = '/DEBUG:NONE')
    elif debug == 1:
        env.Append(CCFLAGS   = '/Zi',
                   LINKFLAGS = '/DEBUG:FULL'
                  )
    elif debug > 1:
        env.Append(CCFLAGS   = '/Zi /D__DEBUG__',
                   LINKFLAGS = '/DEBUG:FULL'
                  )

    if speexdsp > 0:
        env.Append(CCFLAGS = '/DUSE_SPEEXDSP_RESAMPLER')
else:
    env.Append(CCFLAGS = '-O2 -Wall')

    if debug <= 0:
        env.Append(LINKFLAGS = '-s')
    elif debug == 1:
        env.Append(CCFLAGS = '-g')
    else:
        env.Append(CCFLAGS = '-g -D__DEBUG__')

    if speexdsp > 0:
        env.Append(CCFLAGS = '-DUSE_SPEEXDSP_RESAMPLER')

if speexdsp > 0:
    env.Append(LIBS = ['speexdsp'])

if 'PATH_INC' in os.environ:
    env.Append(CPPPATH = os.environ['PATH_INC'].split(os.pathsep))
if 'PATH_LIB' in os.environ:
    env.Append(LIBPATH = os.environ['PATH_LIB'].split(os.pathsep))


if device.endswith('-linux'):
    env.Append(LINKFLAGS  = '-Wl,-z,noexecstack',
               CPPPATH    = ['/usr/include/SDL2', '/usr/local/include/SDL2', '/usr/local/include'],
               LIBPATH    = ['/usr/local/lib'],
               LIBS       = ['SDL2_mixer', 'SDL2', 'pthread', 'm', 'dl']
              )

    if device.startswith('pc-'):
        if prefer_llasm:
            llasm_version = True
        env.Append(CCFLAGS    = '-m32',
                   LINKFLAGS  = '-m32',
                   LLASMFLAGS = '-inline-idiv',
                   LLVMFLAGS  = '-mtriple=i686-unknown-linux-gnu'
                  )
    elif device.startswith('pc64-'):
        if prefer_llasm:
            llasm_version = True
        if prefer_llasm and prefer_ptrofs64:
            use_pic = True
            env.Append(CCFLAGS    = '-m64 -x c++ -fpie -DPTROFS_64BIT',
                       LINKFLAGS  = '-m64 -pie',
                       LLASMFLAGS = '-m64 -inline-idiv -pic -ptrofs',
                       LLVMFLAGS  = '-mtriple=x86_64-unknown-linux-gnu --relocation-model=pic'
                      )
        else:
            base_param = '-no-pie -Wl,-Ttext-segment'
            if not clean:
                process = subprocess.Popen([env['CC'], '--help', '-v'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, env={"PATH": env['ENV']['PATH']})
                (stdout, stderr) = process.communicate()
                if b'-Ttext-segment' not in stdout:
                    base_param = '-Wl,--no-pie,--image-base'
            env.Append(CCFLAGS    = '-m64 -x c++',
                       LINKFLAGS  = '-m64 ' + base_param + ',0x10000000',
                       LLASMFLAGS = '-m64 -inline-idiv',
                       LLVMFLAGS  = '-mtriple=x86_64-unknown-linux-gnu'
                      )
    elif device.startswith('arm-'):
        if prefer_llasm:
            llasm_version = True
        env.Append(ASFLAGS    = '-EL -I arm/',
                   LLASMFLAGS = '',
                   LLVMFLAGS  = ''
                  )
        # see arm/armconf.inc for explanation of these options (and others)
        env.Append(ASFLAGS = '--defsym USE_R9=1 --defsym ALLOW_UNALIGNED_MEMORY_ACCESS=1')
    elif device.startswith('arm64-'):
        llasm_version = True
        if prefer_ptrofs64:
            use_pic = True
            env.Append(CCFLAGS    = '-x c++ -fpie -DPTROFS_64BIT',
                       LINKFLAGS  = '-pie',
                       LLASMFLAGS = '-m64 -inline-idiv -pic -ptrofs',
                       LLVMFLAGS  = '-mtriple=arm64-unknown-linux-gnu --relocation-model=pic'
                      )
        else:
            env.Append(CCFLAGS    = '-x c++',
                       LINKFLAGS  = '-Wl,-Ttext-segment,0x10000000',
                       LLASMFLAGS = '-m64 -inline-idiv',
                       LLVMFLAGS  = '-mtriple=arm64-unknown-linux-gnu'
                      )
    elif device.startswith('riscv64-'):
        llasm_version = True
        use_pic = True
        env.Append(CCFLAGS    = '-x c++ -fpie -DPTROFS_64BIT',
                   LINKFLAGS  = '-pie',
                   LLASMFLAGS = '-m64 -inline-idiv -pic -ptrofs',
                   LLVMFLAGS  = '-mtriple=riscv64-unknown-linux-gnu -mattr=+i,+m,+a,+f,+d,+zicsr,+zifencei,+c --relocation-model=pic'
                  )
elif device.endswith('-windows'):
    if env['CC'] == 'cl':
        env.Append(CCFLAGS   = '/Dmain=SDL_main /MD',
                   LINKFLAGS = '/SUBSYSTEM:WINDOWS /NXCOMPAT /TSAWARE',
                   LIBS      = ['SDL2main', 'SDL2_mixer', 'SDL2', 'zlib', 'user32', 'shell32']
                  )
    else:
        env.Append(CCFLAGS   = '-Dmain=SDL_main',
                   LINKFLAGS = '-mwindows -Wl,--nxcompat,--tsaware',
                   LIBS      = ['mingw32', 'SDL2main', 'SDL2_mixer', 'SDL2', 'z']
                  )

    if device.startswith('pc-'):
        if prefer_llasm:
            llasm_version = True
        if env['CC'] == 'cl':
            env.Append(LINKFLAGS  = '/MACHINE:X86 /DYNAMICBASE:NO /FIXED',
                       LLASMFLAGS = '-inline-idiv',
                       LLVMFLAGS  = '-mtriple=i686-pc-windows-msvc'
                      )
        else:
            env.Append(CCFLAGS    = '-m32',
                       LINKFLAGS  = '-m32',
                       LLASMFLAGS = '-inline-idiv',
                       LLVMFLAGS  = '-mtriple=i686-pc-windows-gnu'
                      )
    elif device.startswith('pc64-'):
        if prefer_llasm:
            llasm_version = True
        use_pic = True
        if env['CC'] == 'cl':
            env.Append(CCFLAGS   = '/TP',
                       LINKFLAGS = '/MACHINE:X64 /LARGEADDRESSAWARE',
                       LLASMFLAGS = '-m64 -inline-idiv',
                       LLVMFLAGS  = '-mtriple=x86_64-pc-windows-msvc'
                      )
        else:
            env.Append(CCFLAGS   = '-m64 -x c++',
                       LINKFLAGS = '-m64',
                       LLASMFLAGS = '-m64 -inline-idiv',
                       LLVMFLAGS  = '-mtriple=x86_64-pc-windows-gnu'
                      )
        if prefer_llasm and prefer_ptrofs64:
            if env['CC'] == 'cl':
                env.Append(CCFLAGS   = '/DPTROFS_64BIT',
                           LINKFLAGS = '/DYNAMICBASE /FIXED:NO /HIGHENTROPYVA',
                           LLASMFLAGS = ' -ptrofs'
                          )
            else:
                env.Append(CCFLAGS   = '-DPTROFS_64BIT',
                           LINKFLAGS = '-Wl,--dynamicbase,--enable-reloc-section,--high-entropy-va',
                           LLASMFLAGS = ' -ptrofs'
                          )
        else:
            if env['CC'] == 'cl':
                env.Append(LINKFLAGS = '/BASE:0x10000000 /DYNAMICBASE:NO /FIXED /HIGHENTROPYVA:NO')
            else:
                env.Append(LINKFLAGS = '-Wl,--image-base,0x10000000,--disable-dynamicbase,--disable-reloc-section,--disable-high-entropy-va')
elif device.endswith('-darwin'):
    llasm_version = True
    use_pic = True
    env.Append(FRAMEWORKPATH = ['/Library/Frameworks'],
               FRAMEWORKS    = ['SDL2_mixer', 'SDL2'],
               CPPPATH       = ['/Library/Frameworks/SDL2.framework/Headers', '/Library/Frameworks/SDL2_mixer.framework/Headers'],
               LIBS          = ['pthread', 'm', 'dl']
              )

    if device.startswith('pc64-'):
        if prefer_ptrofs64:
            env.Append(CCFLAGS    = '-m64 -x c++ -std=c++11 -fpie -DPTROFS_64BIT',
                       LINKFLAGS  = '-m64 -Wl,-pie',
                       LLASMFLAGS = '-m64 -inline-idiv -pic -ptrofs',
                       LLVMFLAGS  = '-mtriple=x86_64-apple-darwin --relocation-model=pic'
                      )
        else:
            env.Append(CCFLAGS    = '-m64 -x c++ -std=c++11 -fno-PIE',
                       LINKFLAGS  = '-m64 -Wl,-pagezero_size,0x110000,-no_pie',
                       LLASMFLAGS = '-m64 -inline-idiv',
                       LLVMFLAGS  = '-mtriple=x86_64-apple-darwin'
                      )
    elif device.startswith('arm64-'):
        env.Append(CCFLAGS    = '-arch arm64 -x c++ -std=c++11 -fpie -DPTROFS_64BIT',
                   LINKFLAGS  = '-arch arm64 -Wl,-pie',
                   LLASMFLAGS = '-m64 -inline-idiv -pic -ptrofs',
                   LLVMFLAGS  = '-mtriple=arm64-apple-darwin --relocation-model=pic'
                  )
elif device == 'pyra':
    if prefer_llasm:
        llasm_version = True
    env.Append(CCFLAGS    = '-DPYRA -pipe -march=armv7ve+simd -mcpu=cortex-a15 -mtune=cortex-a15 -mfpu=neon-vfpv4 -mfloat-abi=hard -mthumb',
               LINKFLAGS  = '-Wl,-z,noexecstack',
               CPPPATH    = ['/usr/include/SDL2'],
               LIBS       = ['SDL2_mixer', 'SDL2', 'pthread', 'm', 'dl'],
               ASFLAGS    = '-EL -march=armv7ve -mcpu=cortex-a15 -mfpu=neon-vfpv4 -mfloat-abi=hard -I arm/',
               LLASMFLAGS = '-inline-idiv',
               LLVMFLAGS  = '-mtriple=thumbv7a-unknown-linux-eabi -mcpu=cortex-a15 -float-abi=hard'
              )
    # see arm/armconf.inc for explanation of these options (and others)
    env.Append(ASFLAGS = '--defsym USE_R9=1 --defsym ALLOW_UNALIGNED_MEMORY_ACCESS=1')
elif device == 'web':
    llasm_version = True
    env['CC'] = 'emcc'
    env['CXX'] = 'em++'
    env['LINK'] = 'em++'
    env['ENV'] = dict(os.environ)

    # files downloaded at init - rest is streamed
    data_embedded_files = ['Albion.cfg', 'ALBION.EXE', 'setup.ini']
    data_preloaded_files = ['XLDLIBS/PICTURE0.XLD']

    embed_flags = ' '.join('--embed-file data/%s@/%s' % (f, f) for f in data_embedded_files)
    preload_flags = ' '.join('--preload-file data/%s@/%s' % (f, f) for f in data_preloaded_files)

    env.Append(CCFLAGS    = '-D__DEBUG__ -m32 -DUSE_SDL2 -sUSE_SDL_MIXER=2 -sSDL2_MIXER_FORMATS=[] -sUSE_SDL=2 -sUSE_ZLIB=1 -pthread -sUSE_PTHREADS=1',
               CPPPATH    = ['brotli/c/include'],
               LINKFLAGS  = '-sUSE_SDL_MIXER=2 -sSDL2_MIXER_FORMATS=[] -sUSE_SDL=2 -sUSE_ZLIB=1 -sCASE_INSENSITIVE_FS=1 -lidbfs.js ' + preload_flags + ' ' + embed_flags + ' --pre-js web/prerun.js --shell-file web/shell.html -m32 -pthread -sUSE_PTHREADS=1 -sALLOW_MEMORY_GROWTH=1 -sDYNAMIC_EXECUTION=0 -sEXIT_RUNTIME=0 -sPTHREAD_POOL_SIZE=0 -sALLOW_BLOCKING_ON_MAIN_THREAD=0 -sEXPORTED_RUNTIME_METHODS=["ccall","cwrap","FS","callMain"] --profiling-funcs',
               LIBS       = ['pthread', 'dl'],
               LLASMFLAGS = '-no-tail-calls',
               LLVMFLAGS  = '-march=wasm32'
              )
    def sync_tree(src_path, dst_path):
        # copies updated files and removes unneeded files
        if os.path.isdir(src_path):
            os.makedirs(dst_path, exist_ok=True)
            src_entries = set(os.listdir(src_path))
            for entry in os.listdir(dst_path):
                if entry not in src_entries:
                    entry_path = os.path.join(dst_path, entry)
                    if os.path.isdir(entry_path):
                        shutil.rmtree(entry_path)
                    else:
                        os.remove(entry_path)
            for entry in src_entries:
                sync_tree(os.path.join(src_path, entry), os.path.join(dst_path, entry))
        else:
            if (not os.path.exists(dst_path)) or (os.path.getmtime(src_path) > os.path.getmtime(dst_path)) or (os.path.getsize(src_path) != os.path.getsize(dst_path)):
                shutil.copy2(src_path, dst_path)

    if not clean:
        resources_dir = 'resources'
        resources_makefile = os.path.join(resources_dir, 'makefile')
        if os.path.isfile(resources_makefile):
            xldlibs_out_dir = os.path.abspath(os.path.join('data', 'XLDLIBS'))
            subprocess.check_call(['make', '-C', resources_dir, 'OUT_DIR=' + xldlibs_out_dir, 'all'])
        elif not os.path.isdir(os.path.join('data', 'XLDLIBS')):
            print("\nWarning: data/XLDLIBS is missing and could not be regenerated. Either run 'git submodule update --init'")
            print(" or provide the contents manually.\n")

        try:
            os.makedirs('publish')
        except OSError:
            pass

        web_static_files = ['style.css', 'controls.js', 'module.js', 'video.js', 'saves.js', 'settings.js', 'share.js', 'mobile.js']
        for web_static_name in web_static_files:
            web_static_src = os.path.join('web', web_static_name)
            if os.path.isfile(web_static_src):
                sync_tree(web_static_src, os.path.join('publish', web_static_name))

        # files streamed at run-time
        publish_data_dir = os.path.join('publish', 'data')
        remote_sources = [('XLDLIBS', os.path.join('data', 'XLDLIBS')),
                           ('MAIN.EXE', os.path.join('data', 'MAIN.EXE')),
                           ('DRIVERS', os.path.join('data', 'DRIVERS'))]
        # embedded files
        embedded_paths = set(['XLDLIBS/PICTURE0.XLD'])

        os.makedirs(publish_data_dir, exist_ok=True)
        for rel_name, src_path in remote_sources:
            if os.path.exists(src_path):
                sync_tree(src_path, os.path.join(publish_data_dir, rel_name))

        video_src_dir = os.path.join('data', 'VIDEO')
        if os.path.isdir(video_src_dir):
            sync_tree(video_src_dir, os.path.join(publish_data_dir, 'VIDEO'))

        manifest = {}
        for rel_name, _ in remote_sources:
            root_path = os.path.join(publish_data_dir, rel_name)
            if os.path.isdir(root_path):
                for dirpath, _dirnames, filenames in os.walk(root_path):
                    for fname in filenames:
                        full_path = os.path.join(dirpath, fname)
                        rel_path = os.path.relpath(full_path, publish_data_dir).replace(os.sep, '/')
                        if rel_path in embedded_paths:
                            continue
                        manifest[rel_path] = os.path.getsize(full_path)
            elif os.path.isfile(root_path):
                manifest[rel_name] = os.path.getsize(root_path)

        with open(os.path.join(publish_data_dir, 'manifest.json'), 'w') as manifest_file:
            json.dump(manifest, manifest_file)
    program_name = 'publish/' + program_name + '.html'

def get_compiler_version(compiler_path, env_path):
    process = subprocess.Popen([compiler_path, '-dumpversion'], stdout=subprocess.PIPE, env={"PATH": env_path})
    (stdout, stderr) = process.communicate()
    if not stdout or stdout.isspace():
        return None
    version = stdout.strip().split(b'.')
    return version

def is_version_ge(version, comparand):
    if version is None or comparand is None:
        return False

    for i in range(len(comparand)):
        if i >= len(version):
            component = 0
        else:
            component = int(version[i])
        if int(comparand[i]) > component:
            return False
        if int(comparand[i]) < component:
            return True
    return True

if not clean and env['CC'] != 'cl' and not use_pic and device != 'web':
    compiler_version = get_compiler_version(env['CC'], env['ENV']['PATH'])
    if is_version_ge(compiler_version, [3, 4]):
        env.Append(CCFLAGS = '-fno-PIE')
    if is_version_ge(compiler_version, [6]):
        env.Append(LINKFLAGS = '-no-pie')

display_objs = SConscript('display/SConscript', exports='device env')
audio_objs = SConscript('audio/SConscript', exports='device env')
input_objs = SConscript('input/SConscript', exports='device env')

# Embed ADLMIDI
plugin_objs = []
if device == 'web':
    mp_dir = '../../../midi-plugins'
    adl_dir = mp_dir + '/libADLMIDI'
    adl_env = env.Clone()
    adl_env['CXX'] = 'em++'
    adl_env.Append(CPPPATH = [adl_dir + '/include', adl_dir + '/src', mp_dir],
                   CXXFLAGS = ' -std=c++11',
                   CPPDEFINES = ['ADLMIDI_DISABLE_OPAL_EMULATOR', 'ADLMIDI_DISABLE_JAVA_EMULATOR',
                                 'ADLMIDI_DISABLE_ESFMU_EMULATOR', 'ADLMIDI_DISABLE_MAME_OPL2_EMULATOR',
                                 'ADLMIDI_DISABLE_YMFM_EMULATOR'])
    adl_sources = [
        'src/adlmidi.cpp', 'src/adlmidi_load.cpp', 'src/adlmidi_midiplay.cpp',
        'src/adlmidi_opl3.cpp', 'src/adlmidi_private.cpp', 'src/adlmidi_sequencer.cpp',
        'src/inst_db.cpp',
        'src/models/model_ail.c', 'src/models/model_apogee.c', 'src/models/model_dmx.c',
        'src/models/model_generic.c', 'src/models/model_hmi_sos.c', 'src/models/model_msadlib.c',
        'src/models/model_oconnell.c', 'src/models/model_win9x.c',
        'src/chips/dosbox_opl3.cpp', 'src/chips/dosbox/dbopl.cpp',
        'src/chips/nuked_opl3.cpp', 'src/chips/nuked/nukedopl3.c',
        'src/chips/nuked_opl3_fast.cpp', 'src/chips/nuked_fast/nukedopl3_fast.c',
        'src/chips/nuked_opl2.cpp', 'src/chips/nuked/nukedopl2.c',
        'src/chips/nuked_cqm.cpp', 'src/chips/nuked_cqm/cqm.c',
    ]
    for s in adl_sources:
        plugin_objs.append(adl_env.Object('midi_build/' + os.path.splitext(os.path.basename(s))[0], adl_dir + '/' + s))
    plugin_objs.append(adl_env.Object('midi_build/midi-adlmidi', mp_dir + '/midi-adlmidi.c',
                                     CPPDEFINES = adl_env['CPPDEFINES'] + ['initialize_midi_plugin=initialize_midi_plugin_adlmidi']))

    # cmake FluidSynth
    fs_src_dir = os.path.abspath(mp_dir + '/fluidsynth')
    fs_build_dir = os.path.abspath('midi_build/fluidsynth-build')
    fs_lib_path = os.path.join(fs_build_dir, 'src', 'libfluidsynth.a')
    if not clean:
        if os.path.isfile(os.path.join(fs_src_dir, 'CMakeLists.txt')):
            # ensure nested submodules are present
            for fs_nested_submodule in ('gcem', 'signalsmith-audio-basics'):
                if not os.path.isfile(os.path.join(fs_src_dir, fs_nested_submodule, 'CMakeLists.txt')):
                    try:
                        subprocess.check_call(['git', '-C', fs_src_dir, 'submodule', 'update', '--init', fs_nested_submodule])
                    except (subprocess.CalledProcessError, OSError) as e:
                        print("\nWarning: could not get midi-plugins/fluidsynth/%s (%s) via git.\n" % (fs_nested_submodule, e))

            emcmake_path = shutil.which('emcmake')
            emmake_path = shutil.which('emmake')
            if (emcmake_path is None) or (emmake_path is None):
                print("\nWarning: emcmake/emmake not found - cannot build FluidSynth.\n")
            else:
                # use the same interpreter
                fs_env_vars = dict(os.environ)
                fs_env_vars['PYTHON'] = sys.executable
                if not os.path.isfile(os.path.join(fs_build_dir, 'CMakeCache.txt')):
                    # configure once
                    fs_compile_flags = '-m32 -pthread -sUSE_PTHREADS=1'
                    subprocess.check_call([emcmake_path, 'cmake',
                        '-S', fs_src_dir, '-B', fs_build_dir,
                        '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_SHARED_LIBS=OFF',
                        # Emscripten's toolchain sets CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY by
                        # default (cross-compiling convention: only look inside the target
                        # sysroot) - which made find_path() reject FluidSynth's own in-tree
                        # gcem/include entirely, even with the submodule properly checked out,
                        # silently falling back to the network download every time regardless.
                        # BOTH restores normal "also look in the given/project paths" behavior.
                        '-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH',
                        '-DCMAKE_C_FLAGS=' + fs_compile_flags, '-DCMAKE_CXX_FLAGS=' + fs_compile_flags,
                        '-Denable-floats=ON', '-Denable-signalsmith=ON',
                        '-Denable-alsa=OFF', '-Denable-aufile=OFF', '-Denable-dbus=OFF', '-Denable-ipv6=OFF',
                        '-Denable-jack=OFF', '-Denable-ladspa=OFF', '-Denable-libsndfile=OFF',
                        '-Denable-midishare=OFF', '-Denable-opensles=OFF', '-Denable-oboe=OFF',
                        '-Denable-network=OFF', '-Denable-oss=OFF', '-Denable-dsound=OFF',
                        '-Denable-wasapi=OFF', '-Denable-waveout=OFF', '-Denable-winmidi=OFF',
                        '-Denable-sdl3=OFF', '-Denable-pulseaudio=OFF', '-Denable-pipewire=OFF',
                        '-Denable-readline=OFF', '-Denable-threads=OFF', '-Denable-openmp=OFF',
                        '-Denable-native-dls=OFF', '-Denable-portaudio=OFF'], env=fs_env_vars)
                # make the lib
                subprocess.check_call([emmake_path, 'make', '-C', fs_build_dir, '-j4', 'libfluidsynth'], env=fs_env_vars)
        elif not os.path.isfile(fs_lib_path):
            print("\nWarning: midi-plugins/fluidsynth could not be built from sources.\n")

    if os.path.isfile(fs_lib_path):
        fs_env = env.Clone()
        fs_env.Append(CPPPATH = [fs_build_dir + '/include', fs_src_dir + '/include', mp_dir])
        plugin_objs.append(fs_env.Object('midi_build/midi-fluidsynth', mp_dir + '/midi-fluidsynth.c',
                                        CPPDEFINES = ['initialize_midi_plugin=initialize_midi_plugin_fluidsynth']))
        env.Append(LIBS = ['fluidsynth'], LIBPATH = [fs_build_dir + '/src'])

    br_dir = 'brotli'
    if os.path.isdir(os.path.join(br_dir, 'c')):
        br_sources = (sorted(str(s) for s in Glob(br_dir + '/c/common/*.c')) +
                      sorted(str(s) for s in Glob(br_dir + '/c/dec/*.c')) +
                      sorted(str(s) for s in Glob(br_dir + '/c/enc/*.c')))
        for s in br_sources:
            # dec/static_init.c and enc/static_init.c share a basename -- prefix with the parent dir.
            obj_name = os.path.basename(os.path.dirname(s)) + '_' + os.path.splitext(os.path.basename(s))[0]
            plugin_objs.append(env.Object('brotli_build/' + obj_name, s))
    elif not clean:
        print("\nWarning: brotli/ is missing - Share will only be able to use deflate, not Brotli."
              " Run 'git submodule update --init games/Albion/SR-Main/brotli' to fetch it.\n")

if llasm_version:
    arch_objs = SConscript('llasm/SConscript', exports='env')
elif device == 'pc-windows' or device == 'pc-linux':
    arch_objs = SConscript('x86/SConscript', exports='device env')
elif device == 'pc64-windows' or device == 'pc64-linux':
    arch_objs = SConscript('x64/SConscript', exports='device env')
else:
    arch_objs = SConscript('arm/SConscript', exports='device env')

# Albion-version recompiled every time
sources = [f for f in Glob('*.c') if os.path.basename(str(f)) != 'Albion-version.c']
version_obj = env.Object('Albion-version', 'Albion-version.c')
env.AlwaysBuild(version_obj)
version_objs = [version_obj]

program = env.Program(program_name, sources + display_objs + audio_objs + input_objs + arch_objs + plugin_objs + version_objs)
if device == 'web':
    env.Depends(program, ['web/prerun.js', 'web/shell.html'])
    if os.path.isfile(fs_lib_path):
        env.Depends(program, fs_lib_path)
    baked_deps = []
    for rel_path in data_preloaded_files + data_embedded_files:
        full_path = os.path.join('data', *rel_path.split('/'))
        if os.path.isdir(full_path):
            baked_deps += Glob(os.path.join(full_path, '*'))
        elif os.path.isfile(full_path):
            baked_deps.append(full_path)
    env.Depends(program, baked_deps)
